services:
  - type: web
    name: bounce-insight-backend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NASA_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /api/health